<?php
global $CONFIG;
$CONFIG['db']['username'] = 'project';
$CONFIG['db']['password'] = 'project';
$CONFIG['db']['host'] = 'localhost';
$CONFIG['db']['name'] = 'manisha_anju';
$CONFIG['site']['default_controller'] = 'site';
$CONFIG['site']['window_title_prefix'] = 'BhargavImpex';
$CONFIG['site']['root'] = dirname(dirname(dirname(__FILE__)));
$CONFIG['site']['app_path'] = $CONFIG['site']['root'].DIRECTORY_SEPARATOR.'app';
$CONFIG['site']['uploads'] = $CONFIG['site']['root'].DIRECTORY_SEPARATOR.'uploads';
$CONFIG['site']['profile'] = $CONFIG['site']['uploads'].DIRECTORY_SEPARATOR.'profile';
$CONFIG['site']['page_shell'] = 'page_layout.php';
$CONFIG['site']['right_sidebar'] = 'site/sidebar/right.php';
$CONFIG['site']['web_root'] = 'http://priya.iz/';
$CONFIG['Engine'] = $CONFIG['site']['root'].DIRECTORY_SEPARATOR.'Engine';
$CONFIG['file']['png'] = $CONFIG['site']['web_root'].'images/image_icon.png';
$CONFIG['file']['jpg'] = $CONFIG['site']['web_root'].'images/image_icon.png';
$CONFIG['file']['jpeg'] = $CONFIG['site']['web_root'].'images/image_icon.png';
$CONFIG['file']['gif'] = $CONFIG['site']['web_root'].'images/image_icon.png';
$CONFIG['file']['zip'] = $CONFIG['site']['web_root'].'images/file_extension_zip.png';
$CONFIG['file']['gz'] = $CONFIG['site']['web_root'].'images/file_extension_zip.png';