<div class="cmpny-desc">
                <h4><p>Bhargavimpex Limited ventured into the world of business in the year 1971 as a manufacturer of cold forged components like free wheels for bi-cycles.  Its products were a global hit as within a very short span of time, it has been able to bag a large number of highly reputed customers from Europe and USA apart from the domestic market.</p>
                <p>After achieving excellence in the field of cold forging, Highway has diversified its activities to manufacture hot forged and precision machined components for automobile and engineering industries.  It has, now, emerged as a much sought after OEM for almost all the major vehicle manufacturers of all segments in India and abroad. </p>
                <p>With a workforce of over 2000 persons, its activities are now spread over three well laid-out sprawling locations in the industrial city of Ludhiana, India and produces millions of hot and cold forged and precision machined components like Crank Shafts, Connecting Rod, Kick Starter Spindle, Arm Assembly for 2 wheelers, Flange Axle, variety of Shafts and Flanges, Sleeves for 4 wheelers, Crank, Piston, C-Block for white goods industries, etc. – to name a few.</p>
                <p>The wide range of products are based on in-house design centers supported by mechanical and manufacturing engineers for the finest design cues – right from raw forgings, semi finished and finished components with a customer centered philosophy.</p>
                <p>Setting the trends, Bhargavimpex Ltd. balances the perfect Man-Machine synergies.   Procedure, process and performance have been the mainstay for our operative zenith.  The blue print for the best components, finest raw material, advanced imported machines and futuristic technologies have ensured operative excellence. These cut down costs, improves processes, increases production, optimize resources and above all, ensures conscientious operation for the environment - in its drive for the operative zenith.</p>
                <p>Consistency and tenacious adherence to the Quality-Precision factor has mapped in internal clients.  Being an ISO/TS:16949 certified Company, modern management systems are in place, further adding ISO :14001 and OHSAS : 18001 certifications.  Quantifying qualitative parameters with a zero tolerance approach, Bhargavimpex Ltd. raises the bar for its own level of perfection, an art that keeps it on the edge, an edge that keeps it ahead of the competition.</p>
                <p>Today, the message of Bhargavimpex Limited and its formidable quality is reaching far and wide and its impeccable brand name gaining ground even in highly developed, sensitive and cost effective markets.   Trusted and tested, Bhargavimpex Ltd. has its way with globally accepted technology, quality, services and time-bound performance.</p>
                </h4>
            </div>
